name: tictactoe
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  bloc: ^9.1.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^9.1.0
  go_router: ^17.0.0
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Gluten
      fonts:
        - asset: assets/fonts/Gluten-Black.ttf
          weight: 900
        - asset: assets/fonts/Gluten-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Gluten-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gluten-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gluten-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gluten-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gluten-Light.ttf
          weight: 300
        - asset: assets/fonts/Gluten-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Gluten-Thin.ttf
          weight: 100
